apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-env
  namespace: argocd # Fixed
spec:
  project: default

  source:
    repoURL: https://github.com/things4Ops/Run-K8s-on-premise
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: test-namespace # Will create namespace and deploy everything here only

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true